import { build } from 'esbuild';
import { cp, mkdir, readFile, writeFile, readdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const output = path.resolve(here, '../../Host/MyAvaloniaManagement/HelpWeb/vendor');
const assets = ['mermaid.js', 'mermaid.js.LEGAL.txt', 'THIRD-PARTY-NOTICES.txt'];
async function copyAsset(source, relative) {
  await cp(source, path.join(output, relative), { recursive: true });
  async function inventory(directory, prefix) {
    for (const entry of await readdir(directory, { withFileTypes: true })) {
      if (entry.isDirectory()) await inventory(path.join(directory, entry.name), `${prefix}/${entry.name}`);
      else assets.push(`${prefix}/${entry.name}`);
    }
  }
  const { stat } = await import('node:fs/promises');
  if ((await stat(source)).isDirectory()) await inventory(source, relative); else assets.push(relative);
}
await mkdir(output, { recursive: true });
// A single classic-script bundle works from file:// without module fetch/CORS dependencies.
await build({
  stdin: { contents: "import mermaid from 'mermaid'; window.mermaid = mermaid;", resolveDir: here },
  bundle: true, format: 'iife', platform: 'browser', target: 'es2022', minify: true,
  outfile: path.join(output, 'mermaid.js'), legalComments: 'linked'
});
for (const name of ['tex-svg.js', 'core.js', 'loader.js', 'startup.js', 'input', 'output', 'a11y', 'ui', 'sre', 'adaptors', 'LICENSE'])
  await copyAsset(path.join(here, 'node_modules/mathjax', name), 'mathjax/' + name);
const fonts = path.join(here, 'node_modules/@mathjax');
await mkdir(path.join(output, 'fonts'), { recursive: true });
for (const name of await readdir(fonts)) {
  if (name.endsWith('-font')) {
    await mkdir(path.join(output, 'fonts', name), { recursive: true });
    for (const asset of ['svg.js', 'svg', 'package.json'])
      await copyAsset(path.join(fonts, name, asset), `fonts/${name}/${asset}`);
  }
}
// Include actual license texts, including transitive packages bundled into Mermaid.
const notices = [];
async function collect(directory) {
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    if (!entry.isDirectory() || entry.name.startsWith('.')) continue;
    const root = path.join(directory, entry.name);
    if (entry.name.startsWith('@')) { await collect(root); continue; }
    try {
      const pkg = JSON.parse(await readFile(path.join(root, 'package.json'), 'utf8'));
      const names = (await readdir(root)).filter(n => /^(licen[cs]e|copying|notice)(\.|$)/i.test(n));
      for (const name of names) {
        try { notices.push(`${pkg.name}@${pkg.version} — ${name}\n${await readFile(path.join(root, name), 'utf8')}`); } catch {}
      }
    } catch {}
    try { await collect(path.join(root, 'node_modules')); } catch {}
  }
}
await collect(path.join(here, 'node_modules'));
await writeFile(path.join(output, 'THIRD-PARTY-NOTICES.txt'), notices.sort().join('\n\n' + '='.repeat(72) + '\n\n'));
const lines = [...new Set(assets)].sort().map(asset => `    <Content Include="HelpWeb/vendor/${asset}" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />`);
await writeFile(path.join(output, '../HelpAssets.props'), '<!-- Generated by tools/help-assets/build.mjs. -->\n<Project>\n  <ItemGroup>\n' + lines.join('\n') + '\n  </ItemGroup>\n</Project>\n');
console.log('Offline help assets built:', output);
