<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Models\SecretVideoPlayer\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\MyAvaloniaManagementCommon\MyAvaloniaManagementCommon.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="LibVLCSharp.Avalonia" Version="3.9.4" />
      <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.21" />
      <PackageReference Include="System.Security.Cryptography.Algorithms" Version="4.3.1" />
    </ItemGroup>

</Project>
