<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\MyAvaloniaManagementCommon\MyAvaloniaManagementCommon.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Avalonia" Version="11.3.5" />
      <PackageReference Include="Avalonia.Controls.TreeDataGrid" Version="11.1.1" />
      <PackageReference Include="Avalonia.Desktop" Version="11.3.5" />
      <PackageReference Include="Avalonia.Diagnostics" Version="11.3.5" />
      <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.5" />
      <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.5" />
      <PackageReference Include="Avalonia.Xaml.Interactions" Version="11.3.0.6" />
      <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
      <PackageReference Include="Dock.Avalonia" Version="11.3.2.2" />
      <PackageReference Include="Dock.Avalonia.Diagnostics" Version="11.3.2.2" />
      <PackageReference Include="Dock.Avalonia.Themes.Fluent" Version="11.3.2.2" />
      <PackageReference Include="Dock.Controls.ProportionalStackPanel" Version="11.3.2.2" />
      <PackageReference Include="Dock.Controls.Recycling" Version="11.3.2.2" />
      <PackageReference Include="Dock.Controls.Recycling.Model" Version="11.3.2.2" />
      <PackageReference Include="Dock.Model.Mvvm" Version="11.3.2.2" />
      <PackageReference Include="EmberDock.Settings" Version="0.0.1" />
      <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
      <PackageReference Include="StaticViewLocator" Version="0.0.1">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>
</Project>
