<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <PlatformTarget>x64</PlatformTarget>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\MyAvaloniaManagementCommon\MyAvaloniaManagementCommon.csproj" />
    </ItemGroup>
    
    <ItemGroup>
      <PackageReference Include="Avalonia" />
      <PackageReference Include="Avalonia.Controls.TreeDataGrid" />
      <PackageReference Include="Avalonia.Desktop" />
      <PackageReference Include="Avalonia.Diagnostics" />
      <PackageReference Include="Avalonia.Fonts.Inter" />
      <PackageReference Include="Avalonia.Themes.Fluent" />
      <PackageReference Include="Avalonia.Xaml.Interactions" />
      <PackageReference Include="CommunityToolkit.Mvvm" />
      <PackageReference Include="Dock.Avalonia" />
      <PackageReference Include="Dock.Avalonia.Diagnostics" />
      <PackageReference Include="Dock.Avalonia.Themes.Fluent" />
      <PackageReference Include="Dock.Controls.ProportionalStackPanel" />
      <PackageReference Include="Dock.Controls.Recycling" />
      <PackageReference Include="Dock.Controls.Recycling.Model" />
      <PackageReference Include="Dock.Model.Mvvm" />
      <PackageReference Include="EmberDock.Settings" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
      <PackageReference Include="Microsoft.Extensions.Hosting" />
      <PackageReference Include="Newtonsoft.Json" />
      <PackageReference Include="StaticViewLocator">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>
</Project>
