<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Host\MyAvaloniaManagementCommon\MyAvaloniaManagementCommon.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="EPPlus" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Styles\" />
    </ItemGroup>
    <ItemGroup>
        <AvaloniaResource Include="Styles/**" />
    </ItemGroup>
</Project>
